### ISSUE TITLE
EB: Pouvoir changer l'ordre des éléments dans la liste d'objet et donc leur disposition

### ISSUE THREAD

**Issue by AudeP** [pandasuite/Studio#1]
Il serait top de pouvoir hiérarchiser les éléments de la liste d'objet directement en glissant leur libellé les uns ou dessus des autres et que cela permette de jouer sur qui est par dessus qui est par dessous (comme les boutons du bandeau d'actions passant à l'avant, passer à l'arrière...)
![capture d ecran 2015-01-29 a 12 08 13](https://cloud.githubusercontent.com/assets/8969531/6002632/65e805b2-aaf5-11e4-860c-95c556f10dcf.png)

**Comment by benjaminbarbe** [comment]
v1.0.11 https://github.com/pandasuite/Studio/commit/77035d74ccd2140e561a0a5f2c28412a7ef02e42
